package org.springframework.data.marklogic.core.mapping;

import java.math.BigInteger;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * --Description--
 *
 * @author Stéphane Toussaint
 */
public abstract class MarklogicSimpleTypes {

    public static final Set<Class<?>> AUTOGENERATED_ID_TYPES;

    static {
        Set<Class<?>> classes = new HashSet<>();
        classes.add(String.class);
        classes.add(BigInteger.class);
        AUTOGENERATED_ID_TYPES = Collections.unmodifiableSet(classes);
    }

    private MarklogicSimpleTypes() {}
}
